- hosts: localhost
  connection: local
  gather_facts: no
  become: false
  vars_files:
    - vault/aws.yml
    - vars/vars-s3.yml
    - vars/vars-hub.yml
  tasks:
  - name: collect Multi-Cluster-HUB version
    include_tasks: ./roles/tools/tasks/mch.yml
  - name: for backup eventually we want create S3
    set_fact:
      CREATE_S3_STORAGE: true
  - include_role:
      name: ./roles/oadp-operator
    when: MCH_VERSION | regex_search("^2\.4\.(.)$") # 2.4.4 requested to create oadp-operator
  - include_role:
      name: ./roles/cluster-backup-operator
  - include_role:
      name: ./roles/oadp-object-storage
  - name: enable Backups
    include_tasks: ./roles/hub-backup/tasks/enable.yml
