- hosts: localhost
  connection: local
  gather_facts: no
  become: false
  tasks:
  - include_role:
      name: ./roles/oadp-operator/tasks/enable.yml
  - include_role:
      name:  ./roles/oadp-object-storage/tasks/configure.yml
  - include_role:
      name: ./roles/restore-hub