apiVersion: oadp.openshift.io/v1alpha1
kind: Velero
metadata:
  namespace: openshift-adp
  name: velero
spec:
  enableRestic: false
  defaultVeleroPlugins:
  - aws
  - openshift
  backupStorageLocations:
  - name: default
    provider: aws
    default: true
    objectStorage:
      bucket: {{ BUCKET }}
      prefix: backups
    config:
      region: {{ STORAGE_REGION }}
      profile: "default"
    credential:
      name: cloud-credentials
      key: cloud
