---

# Create the S3 bucket if needed
- name: Create if not present {{ BUCKET }} in region {{ STORAGE_REGION }}
  amazon.aws.s3_bucket:
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
    name: "{{ BUCKET }}"
    region: "{{ STORAGE_REGION }}"
    state: present
    public_access:
      block_public_acls: true
      ignore_public_acls: true