---
# configure the openshift oadp operator object storage

# Create the S3 bucket if needed
- name: Create if not present {{ BUCKET }} in region {{ STORAGE_REGION }}
  amazon.aws.s3_bucket:
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
    name: "{{ BUCKET }}"
    region: "{{ STORAGE_REGION }}"
    state: present
    public_access:
      block_public_acls: true
      ignore_public_acls: true
  when: CREATE_S3_STORAGE 

- name: check wether s3 {{ BUCKET }} exists or fail
  community.aws.aws_s3_bucket_info:
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
    name: "{{ BUCKET }}"
    region: "{{ STORAGE_REGION }}"
  register: results
  failed_when: results['buckets'] is not defined or (results['buckets']|length == 0)

- name: Create temporary file
  ansible.builtin.tempfile:
    state: file
    suffix: temp
  register: tempfile_1

- name: generate storage secret
  template:
    src: ./roles/oadp-object-storage/tasks/templates/cloud-credentials.j2
    dest: "{{ tempfile_1.path }}"


- name: Create storage secret for 2.4.4
  kubernetes.core.k8s:
    context: "{{ HUB_CONTEXT }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: cloud-credentials
        namespace: openshift-adp
      data:
        cloud: "{{ lookup('file',  '{{tempfile_1.path}}'  ) | b64encode }}"
  when: MCH_VERSION ==  "2.4.4"

- name: Create storage secret for 2.5.0
  kubernetes.core.k8s:
    context: "{{ HUB_CONTEXT }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: cloud-credentials
        namespace: open-cluster-management-backup
      data:
        cloud: "{{ lookup('file',  '{{tempfile_1.path}}'  ) | b64encode }}"
  when: MCH_VERSION ==  "2.5.0" 

- name: Remove tmp credential file
  ansible.builtin.file:
    path: "{{tempfile_1.path}}"
    state: absent


- name:  "If HUB it's 2.4.4 create velero resource"
  kubernetes.core.k8s:
    context: "{{ HUB_CONTEXT }}"
    state: present
    template:
      - path: "velero.yml"  
  when: MCH_VERSION ==  "2.4.4"

- name: "If HUB it's 2.5.0 create DataProtectionApplication"
  kubernetes.core.k8s:
    context: "{{ HUB_CONTEXT }}"
    state: present
    template:
      - path: "DataProtectionApplication.yml"
  when: MCH_VERSION ==  "2.5.0"
